spring:
  # 临时解决doc
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    nacos:
      config:
        group: DEFAULT_GROUP
        server-addr: zmz121.cn:8848
  config:
    import:
      - optional:nacos:chat-service.yaml  # 监听 DEFAULT_GROUP:test.yml